dist: trusty
sudo: required
addons:
  ssh_known_hosts: gps.gistda.org
language: node_js
services:
  - docker
node_js:
  - '7'
env:
  - NODE_ENV=test
script:
  - docker build -t gistda/apis:$TRAVIS_BUILD_NUMBER .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=gistda/apis
  - docker tag $REPO:$TRAVIS_BUILD_NUMBER $REPO:latest
  - docker push $REPO:$TRAVIS_BUILD_NUMBER
  - docker push $REPO:latest
before_deploy:
  - openssl aes-256-cbc -K $encrypted_311107af22ea_key -iv $encrypted_311107af22ea_iv
    -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST -p $SSH_PORT "cd services; ./apis.sh $TRAVIS_BUILD_NUMBER"
  on:
    branch: master
